//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Paket
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир распред.
    /// </summary>
    // *** Start programmer edit section *** (ФормирРаспред CustomAttributes)

    // *** End programmer edit section *** (ФормирРаспред CustomAttributes)
    [AutoAltered()]
    [Caption("Формир распред")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирРаспредE", new string[] {
            "НомерДокРаспр as \'Номер док распр\'",
            "Дата as \'Дата\'",
            "ДокумПостав as \'Докум постав\'",
            "ДокумПостав.НомерДог as \'Номер дог\'",
            "ПунктПогрузки as \'Пункт погрузки\'",
            "ПунктПогрузки.Наименование as \'Наименование\'",
            "СписокКонтей as \'Список контей\'",
            "СписокКонтей.НаимКонт as \'Наим конт\'",
            "СписокБарж as \'Список барж\'",
            "СписокБарж.Производитель as \'Производитель\'",
            "ДокумПостав.Клиенты",
            "ДокумПостав.Клиенты.НаимЗаказ",
            "ДокумПостав.Клиенты.АдресПостав"}, Hidden=new string[] {
            "ДокумПостав.НомерДог",
            "ПунктПогрузки.Наименование",
            "СписокКонтей.НаимКонт",
            "СписокБарж.Производитель"})]
    [MasterViewDefineAttribute("ФормирРаспредE", "ДокумПостав", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерДог")]
    [MasterViewDefineAttribute("ФормирРаспредE", "ПунктПогрузки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ФормирРаспредE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимКонт")]
    [MasterViewDefineAttribute("ФормирРаспредE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Производитель")]
    [View("ФормирРаспредL", new string[] {
            "НомерДокРаспр as \'Номер док распр\'",
            "Дата as \'Дата\'",
            "ДокумПостав.НомерДог as \'Номер дог\'",
            "ПунктПогрузки.Наименование as \'Наименование\'",
            "СписокКонтей.НаимКонт as \'Наим конт\'",
            "СписокБарж.Производитель as \'Производитель\'",
            "ДокумПостав.Клиенты.НаимЗаказ",
            "ДокумПостав.Клиенты.АдресПостав"})]
    public class ФормирРаспред : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерДокРаспр;
        
        private System.DateTime fДата;
        
        private IIS.Paket.ДокумПостав fДокумПостав;
        
        private IIS.Paket.ПунктПогрузки fПунктПогрузки;
        
        private IIS.Paket.СписокКонтей fСписокКонтей;
        
        private IIS.Paket.СписокБарж fСписокБарж;
        
        // *** Start programmer edit section *** (ФормирРаспред CustomMembers)

        // *** End programmer edit section *** (ФормирРаспред CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.Дата Get start)

                // *** End programmer edit section *** (ФормирРаспред.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирРаспред.Дата Get end)

                // *** End programmer edit section *** (ФормирРаспред.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.Дата Set start)

                // *** End programmer edit section *** (ФормирРаспред.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирРаспред.Дата Set end)

                // *** End programmer edit section *** (ФормирРаспред.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокРаспр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.НомерДокРаспр CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.НомерДокРаспр CustomAttributes)
        public virtual int НомерДокРаспр
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.НомерДокРаспр Get start)

                // *** End programmer edit section *** (ФормирРаспред.НомерДокРаспр Get start)
                int result = this.fНомерДокРаспр;
                // *** Start programmer edit section *** (ФормирРаспред.НомерДокРаспр Get end)

                // *** End programmer edit section *** (ФормирРаспред.НомерДокРаспр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.НомерДокРаспр Set start)

                // *** End programmer edit section *** (ФормирРаспред.НомерДокРаспр Set start)
                this.fНомерДокРаспр = value;
                // *** Start programmer edit section *** (ФормирРаспред.НомерДокРаспр Set end)

                // *** End programmer edit section *** (ФормирРаспред.НомерДокРаспр Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.ДокумПостав CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.ДокумПостав CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПостав"})]
        [NotNull()]
        public virtual IIS.Paket.ДокумПостав ДокумПостав
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПостав Get start)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПостав Get start)
                IIS.Paket.ДокумПостав result = this.fДокумПостав;
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПостав Get end)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПостав Set start)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПостав Set start)
                this.fДокумПостав = value;
                // *** Start programmer edit section *** (ФормирРаспред.ДокумПостав Set end)

                // *** End programmer edit section *** (ФормирРаспред.ДокумПостав Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.ПунктПогрузки CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.ПунктПогрузки CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогрузки"})]
        [NotNull()]
        public virtual IIS.Paket.ПунктПогрузки ПунктПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогрузки Get start)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогрузки Get start)
                IIS.Paket.ПунктПогрузки result = this.fПунктПогрузки;
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогрузки Get end)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогрузки Set start)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогрузки Set start)
                this.fПунктПогрузки = value;
                // *** Start programmer edit section *** (ФормирРаспред.ПунктПогрузки Set end)

                // *** End programmer edit section *** (ФормирРаспред.ПунктПогрузки Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Paket.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Get start)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Get start)
                IIS.Paket.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Get end)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Set start)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ФормирРаспред.СписокБарж Set end)

                // *** End programmer edit section *** (ФормирРаспред.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Формир распред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспред.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Paket.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Get start)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Get start)
                IIS.Paket.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Get end)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Set start)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ФормирРаспред.СписокКонтей Set end)

                // *** End programmer edit section *** (ФормирРаспред.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирРаспредE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспредE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспредE", typeof(IIS.Paket.ФормирРаспред));
                }
            }
            
            /// <summary>
            /// "ФормирРаспредL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспредL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспредL", typeof(IIS.Paket.ФормирРаспред));
                }
            }
        }
    }
}
